# Generated by Django 4.2.4 on 2023-10-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginemail', models.EmailField(blank=True, max_length=100, null=True)),
                ('loginpassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
