# Generated by Django 4.2.4 on 2023-10-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_cartdb_delete_logindb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Username',
            new_name='UserName',
        ),
    ]
