# Generated by Django 4.2.4 on 2023-09-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOAPAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='ProductImage')),
            ],
        ),
        migrations.AlterField(
            model_name='shopdb',
            name='CategoryImage',
            field=models.ImageField(blank=True, null=True, upload_to='CategoryImage'),
        ),
    ]
