# Generated by Django 4.2.4 on 2023-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOAPAPP', '0002_productdb_alter_shopdb_categoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
